Refactoring & Industry User Registration & Login
lukebushur/Research-Web-Portal pull request #20
Opened 2024-01-23 19:46 UTC by lukebushur

## Industry User Work
- Created basic industry dashboard component
- Created industry user routes and controllers files in the server
- Upon signing up or logging into an industry account, the server sends the accountType, and the front-end can use this to direct the user to a component associated with their accountType

## Registration & Login Refactoring Work
- Updated the login and signup components to use reactive forms, which are supposed to be faster and more scalable
- Added form validation to the login component
- Added comments to the login and registration components

## Other Changes
- Updated dependencies to eliminate security vulnerabilities on the front-end
- Enabled the Angular compiler's strict mode, which performs more, comprehensive template type-checking
- Formatted several files
- Removed unused imports in several files

2024-01-23 19:58 UTC, prassuresh108 approved these changes

2024-01-23 23:38 UTC, nachobrothernic commented
LGTM!

2024-01-24 04:14 UTC, stierney0505 requested changes
Just add the try catch and you are good for the server

2024-01-25 00:35 UTC, nachobrothernic approved these changes
LGTM

2024-01-25 18:43 UTC, stierney0505 approved these changes

2024-01-25 18:43 UTC, merged